theme: jekyll-theme-cayman
title: Храм во имя святителя Луки (Войно-Ясенецкого)
description:  Сайт прихода храмового корпуса во имя святителя Луки (Войно-Ясенецкого) ФМБЦ им. А.И. Бурназяна ФМБА России.
google_analytics: UA-11312124-9
show_downloads: false
